### PR TITLE
Updated CHANGELOG.md

### PR DESCRIPTION
**Pull request by nuwak**

### CODE REVIEW

**Comment by AmsTaFFix** [comment]
squash all commits to one, and you have excess commit with merge

**Comment by nuwak** [comment]
@AmsTaFFix done

**Comment by AmsTaFFix** [comment]
@nuwak you changed changeling.md, but also edit php file, why?

**Comment by nuwak** [comment]
@AmsTaFFix It is my mistake, I fixed it

**Comment by AmsTaFFix** [comment]
also you should move two points from Unreleased group to 1.4.0, becasuse these two points in that version too

**Comment by nuwak** [comment]
@AmsTaFFix done

**Pull request merged**
